//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    
    public partial class ResAndDevEntitiesNEW : DbContext
    {
        public ResAndDevEntitiesNEW()
            : base("name=ResAndDevEntitiesNEW")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmployeeFinal> EmployeeFinals { get; set; }
        public DbSet<IDList> IDLists { get; set; }
        public DbSet<LoginUser> LoginUsers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<TestModelPrice> TestModelPrices { get; set; }
        public DbSet<user> users { get; set; }
    
        public virtual ObjectResult<GetPriceOuput> getprice()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(GetPriceOuput).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPriceOuput>("getprice");
        }
    }
}
